### ISSUE TITLE
Multi-value headers are mishandled

### ISSUE THREAD

**Issue by gruntster** [pact-foundation/pact-js#964] opened 2022-10-21 06:50 UTC
### Software versions

- **OS**: Ubuntu 22.04.1 LTS
- **Consumer Pact library**: 10.1.4
- **Node Version**: 16.18.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
A multi-value header is matched against the multi-value header of the registered Interaction (v2). Substituting the Pact library with version 9.18.1 works as expected.

### Actual behaviour
A multi-value header of the actual request appears to be processed as a single value that is a combination of all values.
A multi-value header of the expected request is processed as the first value only.

```
  Mock server failed with the following mismatches:

        0) The following request was incorrect:

                GET /dogs

                         1.0 Mismatch with header 'dog-protocol': Expected 'woofruff' to be equal to 'woof'
```

#### package.json
```
{
  "dependencies": {
    "@pact-foundation/pact": "10.1.4",
    "got": "11.8.5",
    "ts-node": "10.9.1"
  }
}
```
#### test.ts
```
import { Interaction, Pact } from "@pact-foundation/pact";
import got from "got";
import * as path from "node:path";

async function test(): Promise<void> {
    const provider = new Pact({
        dir: path.resolve(process.cwd(), "pacts"),
        consumer: "MyConsumer",
        provider: "MyProvider",
        logLevel: "debug"
    });

    await provider.setup();

    await provider.addInteraction(
        new Interaction()
            .given("I have a list of dogs")
            .uponReceiving("a request for all dogs")
            .withRequest({
                method: "GET",
                path: "/dogs",
                headers: { "dog-protocol": "woof, ruff" }
            })
            .willRespondWith({ status: 200 }));

    try {
        await got.get(
            `${provider.mockService.baseUrl}/dogs`, {
                headers: { "dog-protocol": ["woof", "ruff"] },
                retry: 0
            });
    }
    catch (error) { }

    await provider.verify();
    await provider.finalize();
}

void test();
```

#### Steps
1. `npm i`
2. `npx ts-node test.ts`

### Relevant log files

[test.txt](https://github.com/pact-foundation/pact-js/files/9836352/test.txt)

**Comment by mefellows** [comment] 2022-10-24 01:45
Thanks for this.

**Maintainer notes:**

This looks like bug on the JS side. The rust core supports multiple values for a header, but currently that is not exposed to the user.

It looks like on the response side of the check, rust is clever enough to split the header value parts and test each of them. But on the consumer side, it doesn't split the header value (e.g. via the presence of a `,` into its constituent parts) and this might be the cause of the issue.

**Comment by gruntster** [comment] 2022-12-16 11:58
@mefellows This issue is still present in pact 10.4.0. Would it be possible for this to be reopened please?

**Comment by mefellows** [comment] 2022-12-17 09:59
I think

**Comment by mefellows** [comment] 2023-07-09 22:14
After further investigation, the upstream issue is actually https://github.com/pact-foundation/pact-reference/issues/300.

**Comment by mefellows** [comment] 2023-07-17 23:52
The latest Pact JS (via `pact-core` dependency) should address this. Closing.

**Closed by mefellows** 2023-07-17 23:52 UTC
Labels: bug, upstream
