### ISSUE TITLE
Examples to cover more practical interactions

### ISSUE THREAD

**Issue by igwejk** [pact-foundation/pact-js#268] opened 2019-02-14 10:02 UTC
## Expected behaviour

Examples should include ones that factor more practical interactions into consideration.

## Actual behaviour

The examples I've seen only cover GET requests.

## Detail

I'm considering adopting Pact for contract tests. However, I have not seen any example that demonstrates how Pact can typically be used to test interactions where

- a record is created, and verify POST to resource functions as expected
- previously created record is updated, and verify PUT/PATCH to resource functions as expected
- existing entity gets deleted, and verify DELETE to resource functions as expected

## Questions
I might have missed the examples.

- Any pointers to existing examples covering the case described above?
- Where does the documentation cover the mentioned case?

**Comment by mefellows** [comment] 2019-02-14 10:16
The e2e test example has a POST in it, in case you missed that.

As to your other points, there is a good reason why we don't demonstrate stateful interactions in the way you describe.

Pact is designed to test each interaction in isolation from another. 

See https://docs.pact.io/best_practices/consumer#use-pact-for-contract-testing-not-functional-testing-of-the-provider for some more on this, and also read up on provider states which is the mechanism to deal with it directly.

Lastly, join us on slack.pact.io to chat more 😀

**Comment by igwejk** [comment] 2019-02-14 15:24
Thanks for the pointer @mefellows.

> there is a good reason why we don't demonstrate stateful interactions in the way you describe

What could be the reason? Virtually all applications have persistence, and this does factor into how a contract behaves.

I can't test an update contract without being sure there's an existing record to update.

**Comment by mefellows** [comment] 2019-02-14 20:25
@igwejk Pact enforces that no temporal ordering exist in interactions because that is one of the main pain points of traditional practices.

We use [provider states](https://docs.pact.io/getting_started/provider_states) to ensure that when the provider is setup, any state required for that individual interaction is prepared.

> I may agree. But how could one possibly test a resource update contract without being sure there's an existing record to update?

This is the power behind provider states. So to take your example, you specify in the contract that you can get `PUT` a resource on a path e.g. `/products/1234` and in the contract the state is `product 1234 exists`, which returns a `200`. You can then also test the same request with the state `product 1234 does not exist`, and expect a `404`.

The power of this, is that a) you can demonstrate (specification by example) that certain requests can have different responses and b) decouple yourself from ordered based tests that are often the cause of grief for integration testing.

You may still run those types of tests - but _not_ from the consumer, that is the responsibility of the tests of the provider code base. The consumer has no business testing this.

I'm going to close this for now, as these questions are about Pact itself and not this library. Provider states can be a bit tricky, but once you get the hang of it you'll love it. Happy to chat more on Slack with you, as would others in the community.

I'll leave you with a quote from our docs:

> Each interaction in a pact should be verified in isolation, with no context maintained from the previous interactions. Tests that depend on the outcome of previous tests are brittle and land you back in integration test hell, which is the nasty place you're trying to escape by using pacts.

**Closed by mefellows** 2019-02-14 20:25 UTC

**Comment by igwejk** [comment] 2019-02-16 06:32
@mefellows thanks for the clarification.
