### ISSUE TITLE
Contract is updated every time that I execute tests

### ISSUE THREAD

**Issue by leonleo997** [pact-foundation/pact-js#367] opened 2019-09-26 21:47 UTC
Hi,
I would like to know why is modified the contract every time that I execute the tests :(

Thank you

**Comment by mefellows** [comment] 2019-09-26 23:56
Can you please provide more information, for example the code that you are using and what you're expecring? What do you mean by "modified"?

I don't know how to answer this.

**Comment by mefellows** [comment] 2019-10-04 01:00
@leonleo997 can you please provide more information on this issue?

**Comment by TimothyJones** [comment] 2019-11-03 10:59
It's hard to answer this without extra detail, so I'll close it for now. Please feel free to reopen it you have further questions.

**Closed by TimothyJones** 2019-11-03 10:59 UTC
Labels: Awaiting feedback, needs attention

**Comment by Mastermindaxe** [comment] 2020-10-22 09:00
I've got the same problem. What they mean is that after every `npm test` the pact files get "touched" somehow so they pop up as modified in git when in fact they are the exact same files. I think that's what they mean. @mefellows @TimothyJones

**Comment by TimothyJones** [comment] 2020-10-22 10:21
Ah! That makes sense.

I wouldn't recommend checking your contract into git (I suppose you could share contracts this way, but I think it would be a complex workflow).

If you need this for some reason, you may be able to work around this problem. Could you tell us a bit more about your setup? Which test framework are you using to drive Pact? Do you have several test suites writing to the same contract? How is Pact configured?

Also, if having the contract committed is part of your workflow, perhaps we can find a better solution to needing to check it in.

**Comment by mefellows** [comment] 2020-10-22 10:24
> I wouldn't recommend checking your contract into git (I suppose you could share contracts this way, but I think it would be a complex workflow).

Yes, I think some people check them in for reasons like using the contracts for stubbing etc.

I'd be keen to know _what_ is changing, because it might be easy to fix or it might be the way contracts are being used (e.g  with random values for each test). It might just be that permissions are changing (e.g. chmod'ed) or that fields are in random orders. I've not seen this previously, but it's been a while since I checked contracts in.

**Comment by Mastermindaxe** [comment] 2020-10-23 08:44
I've tried to reproduce this now without success. I `git add`ed them and never heard about it again. I didn't even commit them 🤷 Which makes me think it was something on my end...

For anyone that *does* experience this again. Try running the bash command `stat {your file}` before and after you run your tests to see if the file size or modify/change time was altered.

Thank you guys as always for your quick responses!

Cheers!

**Comment by mefellows** [comment] 2020-10-24 00:27
Thanks for getting back @Mastermindaxe !
