### ISSUE TITLE
'neon' is not recognized as an internal or external command when running - npm i @pact-foundation/pact@10.0.0-beta.46  

### ISSUE THREAD

**Issue by DmitriyDmitruk** [pact-foundation/pact-js#737] opened 2021-09-14 08:52 UTC
'neon' is not recognized as an internal or external command when running `npm i @pact-foundation/pact@10.0.0-beta.46`

### Software versions

- **OS**: Windows 10 build 19042.1110
- **Node Version**: 14.17.5
- **NPM Version**: 7.21.1

![Screenshot_114](https://user-images.githubusercontent.com/17577713/133227017-a89092e0-c378-48c3-808f-894919b57aec.jpg)

**Comment by TimothyJones** [comment] 2021-09-14 09:59
10.0.0-beta.46 is currently broken, please use 10.0.0-beta.45

**Comment by TimothyJones** [comment] 2021-09-14 10:06
Sorry about this. The problem is that the current design for native support is to download the artefacts from github. Unfortunately, the artefacts aren't currently building.

The artefacts are there in 10.0.0-beta.45 (which is identical in features, the only thing new in 46 was supposed to be that the artefacts for node 16 were there too).

We're working on removing the need to download native binaries, which will also remove the need for neon.

I'll close this for now, but please reopen if you continue to have issues with beta 45.

**Closed by TimothyJones** 2021-09-14 10:06 UTC
Labels: bug
