### ISSUE TITLE
Migration 9 -> 10 with redhat 

### ISSUE THREAD

**Issue by sergewar** [pact-foundation/pact-js#1032] opened 2022-12-22 17:32 UTC
### Software versions

- **Consumer Pact library**:  9.17.3 -> 10.4.0
- **Node Version**: 16.14.0
- **yarn version**: 1.22.17

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Steps to reproduce

We are trying to bump pact version from “9.17.3” to “10.4.0"
On pact 9.17.3 all works as expected but on 10.4.0 we get an error:
```
/.yarn/unplugged/@pact-foundation-pact-core-npm-13.12.2-ccc2e2dd57/node_modules/@pact-foundation/pact-core/build/Release/libpact_ffi.so: gnu_get_libc_version: symbol not found
```
Image was built with
alpine 3.15
glibc_version 2.34-r0

As resolution (in documentation mentioned that pact not supports alpine but supports OS which supports linking to glibc)  we tried  to migrate to redhat based image (ubi8/nodejs-16-minimal:1-79.1669833161)  but now we get error:
```
Test suite failed to run
libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
[registry.access.redhat.com/ubi8/nodejs-16-minimal:1-79.1669833161](http://registry.access.redhat.com/ubi8/nodejs-16-minimal:1-79.1669833161)
```
glibc_version  2.28

With pact version 9.17.3 both images works as expected. 

Any clues or suggestion how it can be fixed?

**Comment by mefellows** [comment] 2022-12-22 22:46
As you've discovered, we [do not support](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#alpine--docker) Alpine, as you need to compile for each version of Alpine.

I don't seem to be able to pull that image, but it looks like it uses musl. Even if you can install glibc if the OS isn't using it that won't work.

Could you please provide a way for us to reproduce or share the dockerfile here for us to review?

**Comment by sergewar** [comment] 2022-12-23 07:37
We are using Dockerfile like this
```
FROM registry.access.redhat.com/ubi8/nodejs-16-minimal:1-79.1669833161

USER root

RUN microdnf upgrade \
      --refresh \
      --best \
      --nodocs \
      --noplugins \
      --setopt=install_weak_deps=0 && \
    microdnf install shadow-utils && \
    npm install --global yarn && \
    adduser xxx

USER xxx
```

**Comment by sergewar** [comment] 2023-01-09 10:41
Hi @mefellows 
Did you try to run tests with this docker image?

**Comment by mefellows** [comment] 2023-01-09 11:42
Thanks, I haven't sorry as I've been away on holidays. I just tried now and I can't see how it would work, the installation itself is missing Python and many important build tools (such as make, g++ etc.) and so the pact installation fails when it tries to compile the native dependencies. I was able to run a Pact test using the `registry.access.redhat.com/ubi8/nodejs-16` variant which has the basic build dependencies for it to install and run.

Is it possible that you are re-using your node-modules from a previous docker run where musl was linked?

I'll close this as it works. Please re-open with a reproducible example/docker file if you can make it fail in an reasonable way.

**Closed by mefellows** 2023-01-09 11:42 UTC
Labels: bug
