### ISSUE TITLE
Failed case of /test/dsl/integration_with_interceptor.spec.js

### ISSUE THREAD

**Issue by junguchina** [pact-foundation/pact-js#5] opened 2016-07-20 04:43 UTC
`$ ./node_modules/.bin/babel-node ./node_modules/.bin/_mocha -- ./test/dsl/integration_with_interceptor.spec.js`

```
  Pact with Interceptor
    with a single request
      ✓ successfully verifies
    with two requests
      ✓ successfully verifies
    with an unexpected interaction
      ✓ fails verification
    1) "after all" hook

  3 passing (3s)
  1 failing

  1) Pact with Interceptor "after all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by tarciosaraiva** [comment] 2016-07-20 04:58
hi @junguchina have you just pulled and tried to run the tests and that's no working? I need more information:
- what's your node version?
- what's your npm version?

And finally... what are you trying trying to achieve?

**Comment by tarciosaraiva** [comment] 2016-08-01 12:22
@junguchina I'm closing this request as I can't reproduce it locally and Travis has been successful on the last builds.

Please reopen if you have done more investigation on the issue and can share your results.

Cheers

**Closed by tarciosaraiva** 2016-08-01 12:22 UTC
