### ISSUE TITLE
ENOENT when running provider verification

### ISSUE THREAD

**Issue by MarkConway94** [pact-foundation/pact-js#803] opened 2022-01-21 15:00 UTC
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Linux X64
- **Consumer Pact library**: "@pact-foundation/pact": "^9.17.1",
- **Provider Pact library**: "@pact-foundation/pact": "^9.17.1",
- **Node Version**: 14.17.0

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Option providerBaseUrl should set provider base url.

### Actual behaviour

Whatever I put in providerBaseUrl option, it is changed to http://localhost:<randomPort>. This was already reported and closed here https://github.com/pact-foundation/pact-js/issues/337 but we are still seeing it.

### Steps to reproduce

Set the providerBaseUrl and run on an Azure Pipeline agent and see that the provider base url is not set to that value.

### Relevant log files

Hi, we are seeing this issue with our provider test running in an azure pipeline.
We have set the `providerBaseUrl` in the options passed in to the new `Verifier` but a random localhost seems to be used in the pipeline
Here is a console.log of the options we are passing in to create the Verifier
```
  console.log
    ### opts {
      provider: 'MyProvider',
      providerBaseUrl: 'https://www.myprovider.com',
      pactBrokerUrl: 'http://my-pactbroker.com',
      publishVerificationResult: true,
      providerVersion: '1.0',
      timeout: 600000,
      changeOrigin: true,
      logLevel: 'debug',
      verbose: true,
      requestFilter: [AsyncFunction: requestFilter]
    }
```
And here is the error we see, as you can see the only option that we pass in that changes is the providerBaseUrl
```
[2022-01-21 10:04:59.467 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact@9.17.2: Verifying provider
[2022-01-21 10:04:59.475 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact@9.17.2: debug request/response logging enabled
[2022-01-21 10:04:59.479 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Verifying Pacts.
[2022-01-21 10:04:59.481 +0000] INFO (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Verifying Pact Files
[2022-01-21 10:04:59.483 +0000] DEBUG (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Starting pact binary '/usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier', with arguments [--provider-states-setup-url http://localhost:33403/_pactSetup --provider MyProvider --provider-base-url http://localhost:33403 --pact-broker-base-url http://my-pactbroker.com --publish-verification-results true --provider-app-version 1.0 --log-level debug --verbose true]
[2022-01-21 10:04:59.521 +0000] DEBUG (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Created '/usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier' process with PID: undefined
[2022-01-21 10:04:59.522 +0000] ERROR (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: 
    errno: -2
    code: "ENOENT"
    syscall: "spawn /usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier"
    path: "/usr/bin/myagent/_work/4/s/services/node_modules/@pact-foundation/pact-node/standalone/linux-x64-1.88.81/pact/bin/pact-provider-verifier"
    spawnargs: [
      "--provider-states-setup-url",
      "http://localhost:33403/_pactSetup",
      "--provider",
      "MyProvider",
      "--provider-base-url",
      "http://localhost:33403",
      "--pact-broker-base-url",
      "http://my-pactbroker.com",
      "--publish-verification-results",
      "true",
      "--provider-app-version",
      "1.0",
      "--log-level",
      "debug",
      "--verbose",
      "true"
    ]
[2022-01-21 10:04:59.525 +0000] WARN (1230 on ip-x-x-x-x.us-east-2.compute.internal): pact-node@10.17.1: Pact exited with code -2.
```
I've tried setting `changeOrigin` as was mentioned in this thread but that didn't seem to have any effect.

Any other ideas?
Thanks,
Mark

**Comment by TimothyJones** [comment] 2022-01-21 15:46
This is not a bug, you are misinterpreting the debug output. Pact-js runs a proxy server for your provider so that it can catch the state change endpoint and provide convenience methods.

The `ENOENT` error means that pact cannot find the binaries it needs to run. Do you see errors on npm install?

**Comment by TimothyJones** [comment] 2022-01-21 15:57
The correct binaries for your platform are downloaded using the install script. 

* You can confirm whether or not they are there by trying to run the binary listed in that error message (it should print usage information with no arguments)

If the binaries are indeed not there, then here are some additional key points that might help:

* This means pact will not install correctly if you are using `--ignore-scripts`.
* If you are behind a corporate firewall, these instructions may be helpful https://github.com/pact-foundation/pact-js#corporate-proxies--firewalls
* If you are unable to reach the internet during the tests, you can tell pact to use a local copy of the binaries (you will need to provide the exact version it is expecting). See the instructions here https://www.npmjs.com/package/@pact-foundation/pact-node#user-content-pact-download-location

The first place to look is the results of npm install. I suspect there are errors there.

**Comment by MarkConway94** [comment] 2022-01-26 14:00
Thanks @TimothyJones , it looked like we were only partly installing pact.

When we ran `npm ci` we would see these logs
```
/usr/bin/myagent/_work/_tool/node/14.17.0/x64/bin/npm ci
npm WARN lifecycle @my-service/my-app@1.0.0~postinstall: cannot run in wd @my-service/my-app@1.0.0 npm run contracts (wd=/usr/bin/myagent/_work/4/s/services/myApp)

> @pact-foundation/pact-node@10.17.1 postinstall /usr/bin/myagent/_work/4/s/services/myApp/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for linux.
Downloading Pact Standalone Binary v1.88.81 for platform linux from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.81/pact-1.88.81-linux-x86_64.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
```

When we then logged out the contents of the `node_modules/@pact-foundation/pact-node/standalone` directory we saw
```
FOLDER node_modules/@pact-foundation/pact-node/standalone
total 56
-rw-r--r-- 1 root root   109 Oct 26  1985 README.md
-rw-r--r-- 1 root root  1099 Oct 26  1985 install.d.ts
-rw-r--r-- 1 root root 14408 Oct 26  1985 install.js
-rw-r--r-- 1 root root    72 Oct 26  1985 pact-1.88.80-linux-x86.tar.gz.checksum
-rw-r--r-- 1 root root    75 Oct 26  1985 pact-1.88.80-linux-x86_64.tar.gz.checksum
-rw-r--r-- 1 root root    66 Oct 26  1985 pact-1.88.80-osx.tar.gz.checksum
-rw-r--r-- 1 root root    65 Oct 26  1985 pact-1.88.80-win32.zip.checksum
-rw-r--r-- 1 root root    72 Oct 26  1985 pact-1.88.81-linux-x86.tar.gz.checksum
-rw-r--r-- 1 root root    75 Oct 26  1985 pact-1.88.81-linux-x86_64.tar.gz.checksum
-rw-r--r-- 1 root root    66 Oct 26  1985 pact-1.88.81-osx.tar.gz.checksum
-rw-r--r-- 1 root root    65 Oct 26  1985 pact-1.88.81-win32.zip.checksum
```

It seemed like we were missing a few things like `linux-x64-1.88.81` & `pact-1.88.81-osx.tar.gz`.

We tried again but with `npm ci --unsafe-perm`. This time we saw more logs including the confirmation log that pact had been installed.
```
/usr/bin/myagent/_work/_tool/node/14.17.0/x64/bin/npm run ci:unsafe-perm

> @my-service/my-app@1.0.0 ci:unsafe-perm /usr/bin/myagent/_work/4/s/services/myApp
> npm ci --unsafe-perm


> @pact-foundation/pact-node@10.17.1 postinstall /usr/bin/myagent/_work/4/s/services/myApp/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for linux.
Downloading Pact Standalone Binary v1.88.81 for platform linux from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.81/pact-1.88.81-linux-x86_64.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
Finished downloading binary to /usr/bin/myagent/_work/4/s/services/myApp/node_modules/@pact-foundation/pact-node/standalone/pact-1.88.81-linux-x86_64.tar.gz
Extracting binary from /usr/bin/myagent/_work/4/s/services/myApp/node_modules/@pact-foundation/pact-node/standalone/pact-1.88.81-linux-x86_64.tar.gz.
Checksum passed for 'pact-1.88.81-linux-x86_64.tar.gz'.
Extraction done.


### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node


Pact Standalone Binary is ready.
```

And then when logging out the folder we saw there was more stuff there
```
FOLDER node_modules/@pact-foundation/pact-node/standalone
total 7288
-rw-r--r-- 1 root root     109 Oct 26  1985 README.md
-rw-r--r-- 1 root root    1099 Oct 26  1985 install.d.ts
-rw-r--r-- 1 root root   14408 Oct 26  1985 install.js
drwxr-xr-x 3 root root      18 Jan 26 10:28 linux-x64-1.88.81
-rw-r--r-- 1 root root      72 Oct 26  1985 pact-1.88.80-linux-x86.tar.gz.checksum
-rw-r--r-- 1 root root      75 Oct 26  1985 pact-1.88.80-linux-x86_64.tar.gz.checksum
-rw-r--r-- 1 root root      66 Oct 26  1985 pact-1.88.80-osx.tar.gz.checksum
-rw-r--r-- 1 root root      65 Oct 26  1985 pact-1.88.80-win32.zip.checksum
-rw-r--r-- 1 root root      72 Oct 26  1985 pact-1.88.81-linux-x86.tar.gz.checksum
-rw-r--r-- 1 root root 7402902 Jan 26 10:28 pact-1.88.81-linux-x86_64.tar.gz
-rw-r--r-- 1 root root      75 Oct 26  1985 pact-1.88.81-linux-x86_64.tar.gz.checksum
-rw-r--r-- 1 root root      66 Oct 26  1985 pact-1.88.81-osx.tar.gz.checksum
-rw-r--r-- 1 root root      65 Oct 26  1985 pact-1.88.81-win32.zip.checksum
```

We were then able to run the providers tests!
I think we might have to sort out some permissions on the build agent. 
Thanks for your help!

**Comment by TimothyJones** [comment] 2022-01-27 00:22
Looks like nothing was downloaded at all there. Strange that there would be no failure logs - perhaps the permissions issue is silent for some reason.

In the next major release of pact-js, we're bundling the downloads anyway, so these issues will be less common.

I'll close this for now - please feel free to reopen if you think there's something we can fix on the pact side.

**Closed by TimothyJones** 2022-01-27 00:22 UTC
Labels: bug
