### ISSUE TITLE
[V3] provider states with the same name are not exported to pact file

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#848] opened 2022-04-06 11:21 UTC
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**:  Ubuntu 21.04
- **Consumer Pact library**: Pact JS v10.0.0-beta.59
- **Provider Pact library**:  Pact JS v10.0.0-beta.59
- **Node Version**: v16.0.0

### Issue Checklist

Please confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

all provider states are saved to JSON

This would be useful when the provider test needs more than one set of testdata of the same type to be useful. E.g. create multiple files and list them, create multiple users, etc.

### Actual behaviour

only one provider state is saved to JSON

### Steps to reproduce

create multiple provider states with the same name
My use-case is to create multiple files. So I call multiple times 
`provider.given('file exists', { username, password, fileName: resource })`

but in the JSON I only have one providerstate with that name
```
      "providerStates": [
        {
          "name": "the user is recreated",
          "params":...
        },
        {
          "name": "file exists",
          "params": {
            "fileName": "testFolder/文件.txt",
            "password": "test123",
            "username": "test123"
          }
        },
        {
          "name": "resource is shared",
          "params": ...
        }
      ]
```

Making the names of provider states individual makes them appear in the JSON, but that would mean I would also have to have an individual state definition in the provider tests (stateHandlers)

**Comment by mefellows** [comment] 2022-04-27 00:38
We discussed on Slack, but have not yet been able to get the time to dig into it. I think the issue is in the rust core, because I don't think we store provider states anywhere in JS land where a key might override another.

**Comment by individual-it** [comment] 2022-04-27 03:46
I tried to look into it myself yesterday as far as my knowledge goes and I agree with @mefellows in JS I only see the states pushed into an array https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/src/v3/pact.ts#L257

**Comment by mefellows** [comment] 2022-06-26 10:47
Hi @individual-it, having no luck seeing where the problem might lie in JS/Rust land, I attempted to create a repro for this just now (which really ought to have been my first step).

You can see the project here: https://github.com/mefellows/pact-js-repro-848/blob/main/consumer.test.js

If I understand your problem, this test case should reproduce it:

```js
    describe('multiple provider states with same name', () => {
        describe('"file exists" with parameter set 1', () => {
            beforeEach(() =>
                provider
                    .given('file exists', { username: "user", password: "pass", fileName: "resource" })
                    .uponReceiving('a request for a file with user/password')
                    .withRequest({
                        method: 'GET',
                        path: "/file"
                    })
                    .willRespondWith({
                        status: 200,
                    })
            );

            it('returns the animal', () => {
                return provider.executeTest(async (mockserver) => {
                    await axios(`${mockserver.url}/file`)
                });
            });
        });

        describe('"file exists" with parameter set 2', () => {
            beforeEach(() =>
                provider
                    .given('file exists', { foo: "bar" })
                    .uponReceiving('a request for a file with foo/bar')
                    .withRequest({
                        method: 'GET',
                        path: "/file"
                    })
                    .willRespondWith({
                        status: 200,
                    })
            );

            it('returns the animal', () => {
                return provider.executeTest(async (mockserver) => {
                    await axios(`${mockserver.url}/file`)
                });
            });
        });
    });
```

My understanding is that you have multiple tests with the same parameter name, only differentiated by their parameters. With the above tests, I end up with two interactions in the pact file as folows:

```json
{
  "consumer": {
    "name": "test"
  },
  "interactions": [
    {
      "description": "a request for a file with foo/bar",
      "providerStates": [
        {
          "name": "file exists",
          "params": {
            "foo": "bar"
          }
        }
      ],
      "request": {
        "method": "GET",
        "path": "/file"
      },
      "response": {
        "status": 200
      }
    },
    {
      "description": "a request for a file with user/password",
      "providerStates": [
        {
          "name": "file exists",
          "params": {
            "fileName": "resource",
            "password": "pass",
            "username": "user"
          }
        }
      ],
      "request": {
        "method": "GET",
        "path": "/file"
      },
      "response": {
        "status": 200
      }
    }
  ],
  "metadata": {
    "pact-js": {
      "version": "10.0.0-beta.60"
    },
    "pactRust": {
      "ffi": "0.2.4",
      "models": "0.3.1"
    },
    "pactSpecification": {
      "version": "3.0.0"
    }
  },
  "provider": {
    "name": "provider"
  }
}
```

Is it possible you are also provider the same description (`uponReceiving`)? If so, then I believe that is expected behaviour.

**Comment by individual-it** [comment] 2022-07-04 10:46
@mefellows the difference is that in your example you have put the different `.given` calls into different tests, the issue happens if you place them into one

```

                provider
                    .given('file exists', { username: "user", password: "pass", fileName: "resource" })
                    .given('file exists', { foo: "bar" })
                    .uponReceiving('a request to list all files')
                    .withRequest({
                        method: 'GET',
                        path: "/files"
                    })
                    .willRespondWith({
                        status: 200,
                    })
```

I've uploaded an example where it happens to here https://github.com/mefellows/pact-js-repro-848/pull/1/files

**Comment by individual-it** [comment] 2022-07-04 10:48
> Is it possible you are also provider the same description (uponReceiving)? If so, then I believe that is expected behaviour.

yes its part of the same description. If that is the expected behaiviour, how would it be then possible to create multiple items of the same type for a test, e.g. multiple users, files etc?

**Comment by mefellows** [comment] 2022-07-04 11:23
Great - thanks for clarifying, that should help us I hope!

**Comment by mefellows** [comment] 2022-07-04 11:32
This looks to be the culprit: https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/src/mock_server/handles.rs#L415

So I think I know why it worked previously, because it wasn't using the FFI and instead had an intermediary.

The FFI boundary allows you to specify a state description and one set of key/value pairs at a time. If you need multiple, you simply call that function multiple times and it appends the parameters to the state - this is why it's being updated.

@uglyog ignoring the current implementation of `pactffi_given_with_param` and `pactffi_message_given_with_param`, what is your perspective on allowing multiple states on a given interaction with the same name, but different params?

@individual-it could you please elaborate (feel free to update the original request) on why this is desirable? I wonder if it could be achieved in another way?

**Comment by rholshausen** [comment] 2022-07-05 01:45
Provider states were designed to support the same description and different parameters. Think of a state `a user exists` with 3 different sets of parameters with user data. You would expect that all three users be created when the states are executed.

**Comment by individual-it** [comment] 2022-07-05 03:47
@mefellows I think what @rholshausen says pretty much summarizes it, but I also added an other sentence in the original post.
An alternative way to achieve this would be to give an array of data as parameters. Something like:
```
.given('users exists', { users: [ {username: 'Test001', password: '1234'},  {username: 'Test002', password: '4567'}])
```

Not sure if that is supported.

**Comment by mefellows** [comment] 2022-07-27 04:21
I _think_ you could pass in an `[...]` as the second argument, rather than a repeated value. But that's probably not what you're wanting.

**Comment by individual-it** [comment] 2022-09-01 10:58
I've just tried it and it works to send an array to `given()` it results in an object in the JSON
```
      "providerStates": [
        {
          "name": "files exist",
          "params": {
            "0": {
              "content": "",
              "fileName": "testFolder/test space and + and #.txt",
              "username": "testUser1"
            },
            "1": {
              "content": "",
              "fileName": "testFolder/test.txt",
              "username": "testUser1"
            },
            "2": {
              "content": "",
              "fileName": "testFolder/文件.txt",
              "username": "testUser1"
            }
          }
        }
      ],
```

that is not ideal, but might work as a work-around

**Comment by mefellows** [comment] 2022-09-02 08:08
Thanks Artur.

The code does expect a key/value store. So you could probably do this if you wanted a better data structure to navigate?

```
          {
             params: [{
              "content": "",
              "fileName": "testFolder/test space and + and #.txt",
              "username": "testUser1"
            },
            {
              "content": "",
              "fileName": "testFolder/test.txt",
              "username": "testUser1"
            },
            {
              "content": "",
              "fileName": "testFolder/文件.txt",
              "username": "testUser1"
            }
          ]
        }
```

I think Ron has added hooks into the core now to support this scenario, but it will take some work to re-map it, so I will leave open.

**Comment by lhokktyn** [comment] 2023-04-28 11:15
Ran into this today and just confirming some of the above.

Looking at [this code](https://github.com/pact-foundation/pact-reference/blob/pact_consumer-v0.10.8/rust/pact_ffi/src/mock_server/handles.rs#L544-L552), it confirms that subsequent state definitions with the same description will have their parameters merged (by parameter name) with previous definitions.

```javascript
// States
.given("has a user with ID", { id: 1 })
.given("has a user with ID", { id: 2 })

// The "id" from the second will be merged into the "id" of the first, overwriting it
{
  "providerStates": [{
    "name": "has a user with ID",
    "params": {
      "id": 2
    }
  }]
}
```

```js
// States
.given("has a user with ID", [{ id: 1 }, { id: 2 }])
.given("has a user with ID", { id: 3 })

// The first parameters are interpreted as an object rather than array, and merged with the second
{
  "providerStates": [{
    "name": "has a user with ID",
    "params": {
      "0": { "id": 1 },
      "1": { "id": 2 },
      "id": 3
    }
  }]
}
```

**Comment by rholshausen** [comment] 2023-05-02 01:43
I've updated the doc comment on `pactffi_given_with_param`  to indicate that it merges parameter values, and added a second function `pactffi_given_with_params` to allow setting the same provider state multiple times with different parameters.

**Closed** 2024-01-23 12:32 UTC
Labels: bug

**Comment by mefellows** [comment] 2024-02-05 03:12
I've updated Pact JS to use the new method Ron created above, and it seems to create the desired state as expected in the shared example.
