### ISSUE TITLE
Consumer pact verification fails without a meaningful error

### ISSUE THREAD

**Issue by paneq** [pact-foundation/pact-js#24] opened 2017-02-24 15:08 UTC
## 1st

My tests fail with:

```
 FAIL  src/App.test.js
  ● Dog's API › works › successfully verifies

    Pact verification failed - expected interactions did not match actual.
      
      at mockService.verify.then.catch.e (node_modules/pact/src/pact.js:112:17)
```

Without specifying exactly how the expecteded interactions did not match.

I tried to edit `pact.js` around this line of code to tell me more about variable `e` by displaying the key and value of its every property: https://gist.github.com/paneq/480eda0be7d1b456e6bdc70335ed6522 . It does not tell me much. So that is 1st problem which I encountered.

## 2nd

2nd problem is that tests never finish. I mean all tests cases are finished but the process is hanging. I can also see the `node_modules/@pact-foundation/pact-mock-service-linux-x64/lib/ruby/bin.real/ruby` process so my guess is that the reason for the hang is it can't kill the ruby process.

## 3rd

3rd problem that I have (or maybe it is something that I just don't understand)

```
  describe("works", () => {
    beforeAll(done => {
      const interaction = {
        state: 'i have a list of projects',
        uponReceiving: 'a request for projects',
        withRequest: {
          method: 'GET',
          path: '/dogs',
          // headers: { 'Accept': 'application/json' }
        },
        willRespondWith: {
          status: 200,
          headers: { 'Content-Type': 'application/json' },
          body: EXPECTED_BODY
        }
      };
      provider.addInteraction(interaction).then(done, done);
```

The jest version has `then(done, done)` but the mocha version in examples has `provider.addInteraction(interaction).then(() => { done() })` and I wonder why.

Basically with one `then(done)` my tests don't even start because they time out.

When I looked into what is the 2nd callback run with I could see:

```
      provider.addInteraction(interaction).
        then(done, (e)=>{ console.log(e); console.log(e.total); console.log("problem with addInteration"); done(); }).
        catch((e) => { console.log(e); });
```

```
  console.log src/App.test.js:52
    ProgressEvent { isTrusted: [Getter] }

  console.log src/App.test.js:52
    0

  console.log src/App.test.js:52
    problem with addInteration

```

Should that happen?

## Other

What's interesting is that in `logs/mockserver-integration.log` I can see: https://gist.github.com/paneq/08da27b756122cd1348caae911c2c732

I am not sure what's going on but all those problems seem to be related to me.

**Comment by mefellows** [comment] 2017-02-26 06:48
Hi @paneq, which version of Pact are you using? `2.0.x` or previous? (it looks like the latest 2.0.x but just want to confirm).

Are you able to share your test code?

**Comment by paneq** [comment] 2017-02-27 21:18
@mefellows yes pact 2.0 . I invited you to access to https://github.com/arkency/react-example-pact/blob/master/src/App.test.js

**Comment by mefellows** [comment] 2017-03-05 11:21
Hi @paneq, I have been able to clone your repository and reproduced the issue. I'm not familiar enough in the React testing space to be able to diagnose the issue immediately. To my eye it looks good, I'll continue to investigate. Your feedback/efforts to get to the bottom would also be much appreciated.

**Comment by mefellows** [comment] 2017-03-14 21:37
Hi @paneq, have you any update on this?

**Comment by lippea** [comment] 2017-03-19 23:51
For the first question, it's actually an error returned from addInteraction
The error is "{"isTrusted":false}". Not sure what does this mean.

**Comment by gcarling** [comment] 2017-03-24 00:56
@lippea I am experiencing the { isTrusted: false } as well - if anyone has figured out what causes this, help would be greatly appreciated

**Comment by lippea** [comment] 2017-03-27 23:05
@gcarling sorry, couldn't help. I ended up not triggering the interaction from react component, but lower method send the request.

**Comment by mefellows** [comment] 2017-03-27 23:09
That's probably the better way of testing it anyway - from the collaborating component. That being said, I'd still like to understand what's happening here.

**Comment by gcarling** [comment] 2017-03-27 23:14
@paneq @lippea @mefellows I ended up solving this problem by, in my jestConfig, setting `testEnvironment: 'node'`. The issue was that because of jsdom setting `window`, pact was using the XMLHttpRequest from jsdom instead of the node `http` module, and changing this fixed my issue.

**Comment by mefellows** [comment] 2017-03-27 23:20
Ah, thanks @gcarling - note that this is _sort of_ documented already: https://github.com/pact-foundation/pact-js/#note-on-jest

We should make it more explicit (i'll update docs).

**Comment by gcarling** [comment] 2017-03-27 23:27
Ahh wow yeah I did not see that before. I would suggest putting that in the README for the jest example at the top level: I went there but never scrolled down all the way on the main page. That would probably increase visibility for people in a similar situation.

**Comment by mefellows** [comment] 2017-04-15 12:18
Have made the Jest section a bit clearer. Closing.

**Closed by mefellows** 2017-04-15 12:18 UTC
Labels: Awaiting feedback
