### ISSUE TITLE
Mocha tests are not running / timing out

### ISSUE THREAD

**Issue by dervism** [pact-foundation/pact-js#169] opened 2018-04-11 08:50 UTC
## Software versions

Mocha tests are not running on Windows in the latests version of PactJS. See logs - the test are timing out.

* **OS**: Windows 10
* **Consumer Pact library**: Pact JS 5.9.0 and 6.x.x
* **Provider Pact library**: Not relevant
* **Node Version**: 8.9.3

## Expected behaviour

Tests should should run succesfully.

## Actual behaviour

Mocha is timing out. 

By setting a long timout, I can see that the Pact-server responds when quering via browser. However, no interactions are added. The promise returned by ` provider.setup()` are never resolved.

## Steps to reproduce

Run the mocha example via `npm test` on a fresh copy of pactjs repo on windows.

## Relevant log files

[pact-mocha-timeout-consolelog.txt](https://github.com/pact-foundation/pact-js/files/1897994/pact-mocha-timeout-consolelog.txt)

**Comment by mefellows** [comment] 2018-04-11 12:55
Hi @dervism, thanks for taking the time to post this issue and #170. We'll get to the bottom of both.

On first glance at your logs, it seems it is starting the mock service _twice_ - that shouldn't happen, and may be the cause of your problems (it also may just be a symptom). Are you able to share a reproduceable project we can use?

I'm currently at AWS Summit this week and won't have time to look at the issue in any depth, but if the promise isn't resolving it might also be buried away in `pact-node` somewhere (JS wrapper for the Ruby CLI).

If you haven't already, try setting your log level to `DEBUG` and see what it's trying to do and if it spits out anything that might be useful.

**Comment by mefellows** [comment] 2018-04-11 12:57
Scrap the two provider starts - obviously they are the two tests and I didn't notice the ports were _different_ - this is why you don't debug at 11pm after a big day. TBC....

**Comment by dervism** [comment] 2018-04-11 13:48
Yes that is correct. The Mocha example has two tests that demonstrates merging.

**Comment by dervism** [comment] 2018-04-12 09:28
@mefellows No interactions are added to the mock server. I ran Mocha with a long timout and made a manuel query to the mock server through the browser giving me a resonse saying "{"message":"No interaction found for GET /dogs","interaction_diffs":[]}". For some reason [this line](https://github.com/pact-foundation/pact-js/blob/master/examples/mocha/test/get-dogs.spec.js#L30) in get-dogs.spec.js never completes. I have attached an updated example here (the existing example in the repo is outdated).
[mocha2.zip](https://github.com/pact-foundation/pact-js/files/1902234/mocha2.zip)

How important is node-gyp for the current versions of pact-js and pact-node? I can see the following error message now when I run `npm install` in the Windows command line

```bash
C:\pact-js\examples\mocha2\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Users\dervis\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\dervis\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Bygger prosjektene i denne løsningen sekvensielt. Legg til /m-bryteren for å bygge prosjektene parallelt.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the c
omponent to the system path if it is installed elsewhere.  [C:\pact-js\examples\mocha2\node_modules\dtrace-provider\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\dervis\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dervis\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\pact-js\examples\mocha2\node_modules\dtrace-provider
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Closed** 2018-05-29 13:04 UTC
Labels: Triage

**Comment by mefellows** [comment] 2018-05-29 13:05
Thanks for closing @dervism , did you get to the bottom of it?

**Comment by dervism** [comment] 2019-01-15 13:42
@mefellows No. This is still a problem even after upgrading to latest version of Pact (7.2.0). We decided to not continue using PactJS because of this issue.

I just tried again now with the latest version to see if it would work, but no luck.

**Comment by dervism** [comment] 2019-01-17 11:45
@mefellows: Everything works as excepted on Mac and Linux. It's clearly a problem with the Windows infrastructure (probably some proxy issue) on our side. Keeping this issue closed. :-)
