### ISSUE TITLE
publish jest example pact file to broker error

### ISSUE THREAD

**Issue by shishangx** [pact-foundation/pact-js#250] opened 2018-11-15 16:02 UTC
## Software versions

* **OS**: e.g. Mac OSX 10.14.1
* **Consumer Pact library**: git pull to get new version
* **Provider Pact library**: git pull to get new version
* **Node Version**: `9.3.0`

## Expected behaviour

be published successfully.

## Actual behaviour
throw out some error.

## Steps to reproduce

1.try the jest example.
2.create the pact json successfully.
3.use the 'npm run publish:pact' to publish the pact file to local broker.then throw some error.

## Relevant log files
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'publish:pact' ]
2 info using npm@6.4.1
3 info using node@v9.3.0
4 verbose run-script [ 'prepublish:pact', 'publish:pact', 'postpublish:pact' ]
5 info lifecycle jest@1.0.0~prepublish:pact: jest@1.0.0
6 info lifecycle jest@1.0.0~publish:pact: jest@1.0.0
7 verbose lifecycle jest@1.0.0~publish:pact: unsafe-perm in lifecycle true
8 verbose lifecycle jest@1.0.0~publish:pact: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/xxx/Desktop/test1/pact-js/examples/jest/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xxx/Desktop/android_sdk/android-sdk-macosx/platform-tools:/Users/xxx/Desktop/android_sdk/android-sdk-macosx/tools:/Library/Frameworks/Mono.framework/Versions/5.14.0/bin
9 verbose lifecycle jest@1.0.0~publish:pact: CWD: /Users/xxx/Desktop/test1/pact-js/examples/jest
10 silly lifecycle jest@1.0.0~publish:pact: Args: [ '-c', 'node ./publish.js' ]
11 silly lifecycle jest@1.0.0~publish:pact: Returned: code: 1  signal: null
12 info lifecycle jest@1.0.0~publish:pact: Failed to exec publish:pact script
13 verbose stack Error: jest@1.0.0 publish:pact: `node ./publish.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid jest@1.0.0
15 verbose cwd /Users/xxx/Desktop/test1/pact-js/examples/jest
16 verbose Darwin 18.2.0

**Comment by mefellows** [comment] 2018-11-16 09:46
Just in case, the publish for this example is/was designed to work with a local broker, have you got one running on port `3000`? 

Also, could you please set the pact-node logger to DEBUG and share that output? That will help us further narrow things down.

**Comment by shishangx** [comment] 2018-11-17 15:16
thank for your response, actually i have some issues:

firstly, i built a local broker based on the instruments:
https://github.com/pact-foundation/pact_broker
and i start the broker server with the command: 'bundle exec rackup -p 8889'

the broker start successfully, i can access the websitte and upload the pact files by consumer produced(this process produced some errors like the PR i asked).but  i can get the latest version pact from the address:
http://localhost:8889/pacts/provider/tokenProvider/consumer/tokenConsumer/latest

secondly,  i installed the pact verified based on the instruments:
https://github.com/pact-foundation/pact-provider-verifier

and i run the pact verification command like this:
pact-provider-verifier 
 http://localhost:8889/pacts/provider/tokenProvider/consumer/tokenConsumer/latest --provider-base-url https://localhost:8889

i am pretty sure,  the '--provider-base-url'  param is wrong, but i dont know the real is.

attached my pact-node DEBUG log info:
**1. publish pact file to broker:**

    Tagging version 2.0.3 of tokenConsumer as "prod"
    Tagging version 2.0.3 of tokenConsumer as "test"
    Publishing tokenConsumer/tokenProvider pact to pact broker at http://localhost:8889
    The given version of pact is already published. Overwriting...
    The latest version of this pact can be accessed at the following URL (use this to configure the provider verification):
    http://localhost:8889/pacts/provider/tokenProvider/consumer/tokenConsumer/latest

/Users/xxx/Desktop/test1/pact-js/node_modules/q/q.js:155
                throw e;
                ^
Error: Unhandled Promise Rejection: ReferenceError: done is not defined
    at process.<anonymous> (/Users/xxx/Desktop/test1/pact-js/node_modules/@pact-foundation/pact-node/standalone/install.js:263:11)
    at process.emit (events.js:159:13)
    at /Users/xxx/Desktop/test1/pact-js/node_modules/q/q.js:1079:25
    at runSingle (/Users/xxx/Desktop/test1/pact-js/node_modules/q/q.js:137:13)
    at flush (/Users/xxx/Desktop/test1/pact-js/node_modules/q/q.js:130:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jest@1.0.0 publish:pact: `node ./publish.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jest@1.0.0 publish:pact script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-11-17T13_59_31_517Z-debug.log

in the '2018-11-17T13_59_31_517Z-debug.log', contents like i attached above.

**2. provider pact verified:**
i input command like this:
'
pact-provider-verifier http://localhost:8889/pacts/provider/tokenProvider/consumer/tokenConsumer/latest --provider-base-url http://localhost:8889/pacticipants/tokenProvider
'
but can not get the provider, the code thows out errors info, like below:
'
 1) Verifying a pact between tokenConsumer and tokenProvider Given i have a list of eth tx a request for eth tx with POST /rpc returns a response which has status code 200
     Failure/Error: expect(response_status).to eql expected_response_status

       expected: 200
            got: 404

       (compared using eql?)
     # /usr/local/lib/ruby/gems/2.5.0/gems/pact-provider-verifier-1.20.0/bin/pact-provider-verifier:3:in `<top (required)>'
     # /usr/local/bin/pact-provider-verifier:23:in `load'
     # /usr/local/bin/pact-provider-verifier:23:in `<main>'
'

**Comment by mefellows** [comment] 2018-11-17 17:59
Thanks, did you modify the js code? It seems to be complaining abouta done callback not being defined (there is a separate issue with pact node that swallows the root cause of the exception but it's likely to be in the test code)

**Comment by mefellows** [comment] 2018-11-17 18:05
Also, the providerBaseUrl is the http URL of your running API orovider for verification.

**Comment by shishangx** [comment] 2018-11-18 16:55
> Thanks, did you modify the js code? It seems to be complaining abouta done callback not being defined (there is a separate issue with pact node that swallows the root cause of the exception but it's likely to be in the test code)

thanks, could you pls tell me which files you meant. the files in  the _test_ folder ?

**Comment by shishangx** [comment] 2018-11-18 16:58
> Also, the providerBaseUrl is the http URL of your running API orovider for verification.

i dont understand this sentense. you mean that  i should run another provider server or write a provider code? like the 'e2e' ?

**Comment by mefellows** [comment] 2018-11-22 05:35
OK I'm confused:

> secondly, i installed the pact verified based on the instruments:
> https://github.com/pact-foundation/pact-provider-verifier
> ...
> and i run the pact verification command like this:
> pact-provider-verifier
> http://localhost:8889/pacts/provider/tokenProvider/consumer/tokenConsumer/latest --provider-base-url https://localhost:8889

Why are you doing these things with the JS project? IS that just to verify the behaviour of Pact JS? 

To be clear, you don't need to manually invoke those tools from the command line to write pact testts.

> i dont understand this sentense. you mean that i should run another provider server or write a provider code? like the 'e2e' ?

No. To perform provider verification, you need to have a running provider that Pact can replay the interactions against (the requests that get issued are from the pact files). The flag `providerBaseUrl` tells the Pact verification system where to find your running provider to test.

The e2e test automatically starts the provider for you.

**Comment by shishangx** [comment] 2018-11-24 05:17
> The e2e test automatically starts the provider for you.

thanks for your paticent reply:)
in my project, i use the jest to do unit test, so i care about the jest example, but i can not find the publish and provider details in this jest example. i am confused too.

Based on your advice, i check the e2e example with macha test framework, may i  transfer the provider code to jest project? i mean that i should write the full response info with jest to fullfill my project?

**Comment by mefellows** [comment] 2018-11-25 05:16
No worries at all @shishangx!

> Based on your advice, i check the e2e example with macha test framework, may i transfer the provider code to jest project? i mean that i should write the full response info with jest to fullfill my project?

Yes, there is nothing special about Jest or Mocha. The idea is just to help people see how Pact fits in with their framework of choice.

The Jest example doesn't contain a _provider verification_ example, but that's because it's a fairly trivial job. Take a look at the [E2E provider spec](https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/provider.spec.js) for how to do this.

Similarly, feel free to use the same [publish](https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/publish.js) script from e2e and push to our hosted test broker if that helps too.

Hope this helps?

**Comment by shishangx** [comment] 2018-11-25 15:00
> No worries at all @shishangx!
> 
> > Based on your advice, i check the e2e example with macha test framework, may i transfer the provider code to jest project? i mean that i should write the full response info with jest to fullfill my project?
> 
> Yes, there is nothing special about Jest or Mocha. The idea is just to help people see how Pact fits in with their framework of choice.
> 
> The Jest example doesn't contain a _provider verification_ example, but that's because it's a fairly trivial job. Take a look at the [E2E provider spec](https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/provider.spec.js) for how to do this.
> 
> Similarly, feel free to use the same [publish](https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/publish.js) script from e2e and push to our hosted test broker if that helps too.
> 
> Hope this helps?

ok,thank you very much! honestly~

**Comment by mefellows** [comment] 2018-11-26 06:19
No worries. I'm going to close this for now, but feel free to jump onto our [Slack channel](slack.pact.io) and we can always chat further there (there are many others too :))

**Closed by mefellows** 2018-11-26 06:19 UTC
Labels: Awaiting feedback, Triage
