### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings' from 'dtrace-provider.js'

### ISSUE THREAD

**Issue by felipecao** [pact-foundation/pact-js#63] opened 2017-07-06 04:48 UTC
Hello everyone!

I wanted to create a really simple React app and add a Pact test on top of it, but I'm having some trouble making Pact play along well with Jest.

So i started by using https://github.com/facebookincubator/create-react-app to create that React app. It generates a small React app containing basically two classes under `/src`: `App.js` & `App.test.js`. If I run `npm test`, everything runs smooth.

Then I ran `npm install --save-dev pact` to install Pact.

Next thing I did was editing `App.test.js` to just import Pact, nothing else, this is how the test looks like:

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

import pact from 'pact'; // this is the only change I introduced

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
});
```

Now if I run `npm test` again, the test crashes with this error message:
```
  console.error node_modules/dtrace-provider/dtrace-provider.js:26
    { Error: Cannot find module './build/Release/DTraceProviderBindings' from 'dtrace-provider.js'
        at Resolver.resolveModule (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-resolve/build/index.js:179:17)
        at Resolver._getVirtualMockPath (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-resolve/build/index.js:296:23)
        at Resolver._getAbsolutPath (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-resolve/build/index.js:279:10)
        at Resolver.getModuleID (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-resolve/build/index.js:252:31)
        at Runtime._shouldMock (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-runtime/build/index.js:574:37)
        at Runtime.requireModuleOrMock (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-runtime/build/index.js:402:14)
        at Object.<anonymous> (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Runtime._execModule (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-runtime/build/index.js:513:13)
        at Runtime.requireModule (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-runtime/build/index.js:329:14)
        at Runtime.requireModuleOrMock (/Users/felipe/workspace/lixao/pact-js-react-issue/node_modules/jest-runtime/build/index.js:405:19) code: 'MODULE_NOT_FOUND' }
```

Am I doing anything wrong here?

I tried `npm install --save dtrace-provider` but that didn't change anything. I've also tried doing what's documented at https://github.com/pact-foundation/pact-js#note-on-jest, and no luck.

Thanks a lot for the excelent work with the whole Pact family!

**Comment by jonathanconway** [comment] 2017-07-06 06:48
Having the same issue here.

**Comment by mefellows** [comment] 2017-07-08 05:40
Cool, I have been able to repro this. Marking as bug.

For me the tests still work, this is more of an annoying output. Seemingly this issue is quite frequent.

I'm guessing it's related to `pact-node` which uses `bunyan` under the hood.

**Comment by mefellows** [comment] 2017-07-08 06:14
Upon investigation, it seems that bunyan has an optional dependency on `dtrace-provider` which doesn't seem to reliably compile/work on OSX. This appears to be a [very](https://github.com/trentm/node-bunyan/issues/216) [common](https://github.com/trentm/node-bunyan/issues/60) [issue](https://github.com/react-community/create-react-native-app/issues/135) related to the [dtrace provider](https://github.com/chrisa/node-dtrace-provider/issues/71).

As you can see, when installing pact it comes along for the ride:
```
npm i pact
...
my-app@0.1.0 /private/tmp/my-app
├── node-pre-gyp@0.6.36
└─┬ pact@2.6.0
  └─┬ @pact-foundation/pact-node@4.10.0
    ├─┬ @pact-foundation/pact-mock-service@2.1.0
    │ └── @pact-foundation/pact-mock-service-darwin@2.1.0
    ├─┬ @pact-foundation/pact-provider-verifier@1.3.0
    │ └── @pact-foundation/pact-provider-verifier-darwin@1.3.0
    └─┬ bunyan@1.8.10
      └── dtrace-provider@0.8.3
```
I've tried all of the suggestions and nothing worked, manually running the compilation didn't fail aside from a few spurious warnings and created what looked like bindings, just not in the intended location. 

This workaround worked for me, although it's an obviously crappy solution:

```
npm uninstall bunyan && npm i bunyan --no-optional
```

Curious though, I'm not sure why specifically in this configuration it warns.

**Comment by felipecao** [comment] 2017-07-10 06:15
I figured out that work around this issue we just need to create a separate script, one that ignores Jest all together.

What I did was moving my Pact tests to `src/pacts` and then added a script to my `package.json`, like this:

```
"scripts": {
    ... 
    "pacts": "BABEL_ENV=pacts ./node_modules/.bin/mocha --recursive --compilers js:babel-core/register \"pacts/**/*.pact.js\" --timeout 10000"
  },
```

Then, if I run `npm run pacts`, my Pact tests run fine and I don't need to change anything for the tests created by `create-react-app` to work.

**Comment by mefellows** [comment] 2017-07-16 03:52
Thanks @felipecao, great find - I'll update the docs with this (somewhere).

**Comment by kevinbader** [comment] 2018-01-08 17:20
Please re-open this, the error is still there. Also, the [bunyan issue](https://github.com/trentm/node-bunyan/issues/216) is open since January 2015, so I guess the best solution would be to get rid of the dependency, if possible (haven't checked the code yet).

Steps to reproduce:

- Copy the [official Jest example](https://github.com/pact-foundation/pact-js/blob/master/examples/jest/)
- Replace the Pact import in [the test](https://github.com/pact-foundation/pact-js/blob/master/examples/jest/__tests__/index.spec.js) with `const Pact = require('@pact-foundation/pact')`
- Install Pact and invoke tests:
```
yarn add --dev @pact-foundation/pact
yarn test
```

=> the reported "DTraceProviderBindings" error appears.

**Comment by mefellows** [comment] 2018-01-11 21:30
The issue is in upstream `pact-node` package - perhaps we need to look at removing it from there.

**Comment by mefellows** [comment] 2018-01-11 21:30
cc: @mboudreau

**Closed** 2018-02-28 07:23 UTC
Labels: enhancement

**Comment by mefellows** [comment] 2018-02-28 07:45
Release `v5.7.0` with this change @mbark.

**Comment by mbark** [comment] 2018-02-28 12:43
Thank you for the fast merge, everything looks good now! ⭐️

**Comment by mefellows** [comment] 2018-02-28 20:25
👍
