### ISSUE TITLE
Pact files are not placed in the configured folder

### ISSUE THREAD

**Issue by thombergs** [pact-foundation/pact-js#106] opened 2017-10-04 10:44 UTC
When creating pact files from within a unit test, the generated pact files are always placed in the main folder of my angular project. Configuring the `dir` property as shown below, does not bring any change.

```typescript
provider = Pact({
      consumer: 'client',
      provider: 'server',
      web: true,
      port: 1234,
      dir: "pacts"
    });
```
With above configuration I would expect the pact files to be created in the "pacts" subfolder of my project, but they are created in the main folder. This makes it hard to publish the pact files to a broker since I cannot just take all files in a specific folder but have to list each file explicitly.

I use the following versions:
* @pact-foundation/karma-pact: 1.0.0
* @pact-foundation/pact-node: 4.12.0
* pact-web: 3.0.1

**Comment by lirantal** [comment] 2017-10-04 15:37
you can use `process.cwd()` or `__dirname` to custom the folder's place.

**Comment by thombergs** [comment] 2017-10-04 18:19
Yes, but where do I configure the target folder? The "dir" property in the above code snippet has no effect.

**Comment by lirantal** [comment] 2017-10-04 23:15
maybe it's a regression but it works for me, I simply set the `dir` property to wherever I want to save the pact files and they're written there once `finalize()` is called.

**Comment by bethesque** [comment] 2017-10-05 01:03
Is it dir or pactDir?

**Comment by bethesque** [comment] 2017-10-05 01:04
You're right, it's dir, I've found the docs.

**Comment by bethesque** [comment] 2017-10-05 01:13
Do we have example code in the js repo that we can use to replicate?

**Comment by lirantal** [comment] 2017-10-05 08:37
@bethesque https://github.com/pact-foundation/pact-js/blob/master/examples/ava/test/index.spec.js

**Comment by thombergs** [comment] 2017-10-05 10:16
Seeing that code snippet, it might really be a regression. Before we updated pact-web to 3.0 the pact files were placed into the default "pacts" folder. Now, they are just placed in the main folder.

**Comment by mefellows** [comment] 2017-10-05 10:18
Interesting, are you using `karma-pact` as well perchance?

**Comment by thombergs** [comment] 2017-10-05 15:28
yes, @pact-foundation/karma-pact: 1.0.0

**Comment by mefellows** [comment] 2017-10-06 11:20
The E2E tests and current karma also have this option set, so I'm pretty sure it's not in the `pact` package (or at least, it's internally consistent).

I think the problem might be with the recent refactor of `karma-pact`. Rather than configuring this in the client spec itself, the config should move into the `karma.conf.js` file, something like this:

```js
module.exports = function (config) {
  config.set({
    frameworks: ['jasmine', 'pact'],

    // Pact options go here (this used to be defined the spec itself)
    pact: {
    	port: 1234,
    	consumer: "some-consumer",
    	provider: "some-provider",
        dir: "pacts"
    }
  });
};
```

**Comment by thombergs** [comment] 2017-10-06 12:08
Works. 

Thanks a lot!

**Comment by mefellows** [comment] 2017-10-06 12:20
Great!

I'm going to re-open, so that I can track an update to the Karma examples so we have something people can use as a reference, and also to update the docs at `karma-pact` repository.

**Comment by mefellows** [comment] 2017-10-06 12:20
cc: @mboudreau.

**Comment by mefellows** [comment] 2017-10-17 10:45
Working examples now committed in master. Closing!

**Closed by mefellows** 2017-10-17 10:45 UTC
Labels: Documentation, enhancement
