### ISSUE TITLE
No interaction found for POST /api/endpoint 

### ISSUE THREAD

**Issue by erickbelfy** [pact-foundation/pact-js#769] opened 2021-11-15 20:44 UTC
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Mac OSX Big Sur 11.2.3_
- **Consumer Pact library**:     "@pact-foundation/pact": "^9.16.5",
- **Node Version**: `v16.11.1`

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour
Pact should validate the pacts accordingly

### Actual behaviour

the console outputs that there's no interactions for `/api/endpoint` it returns this:

```
 -[
             -  {
             -    "accountUuid": "something",
             -    "realm": "DIstring",
             -    "userUuid": "UUID"
             -  },
             -]
             +{
             +  "message": "No interaction found for POST /api/endpoint",
             +  "interaction_diffs": [,
             +
             +  ]
             +}
```
### Steps to reproduce
this given code from the pact-workshop with small changes

```
endpoint router

import { Router } from 'express';
import { methodNotAllowed } from './api-helpers';
import SignupAPI from './signup';
import Customer from '../../models/Customer';

const router = Router();

export default router;
const endpointService = new SignupAPI({BASE_URL: 'http://myserver.com:9292'});

router
  .route('/api/endpoint')
  .get(methodNotAllowed)
  .put(methodNotAllowed)
  .post(async (req, res) => {
    try {
      const customer = new Customer(req.body);
      const newAccount = await endpointService.createAccount({ ...customer });
      res.status(201).send(newAccount);
    } catch ({ extensions: { response } }) {
      res.status(response.status).send(response.body);
    }
  })
  .delete(methodNotAllowed);

```

```
service that calls another API gateway

import { RESTDataSource } from 'apollo-datasource-rest';


export default class Signup extends RESTDataSource {
  constructor({ BASE_URL }) {
    super();
    this.baseURL = BASE_URL;
    this.initialize({ cache: undefined, context: undefined });
  }

  // eslint-disable-next-line class-methods-use-this
  willSendRequest(request) {
    request.headers.set('Accept', 'application/json');
    request.headers.set('Content-Type', 'application/json');
  }

  async createAccount(body) {
    return this.post('/v1/external-api', body);
  }
}


```
```
import { Verifier } from '@pact-foundation/pact';
import express from 'express';
import apiRoutes from './routes/api';

// Setup provider server to verify
const app = express();
app.use(apiRoutes);

const server = app.listen('8080');

describe('Pact Verification', () => {
  it('validates the expectations of ProductService', () => {
    const opts = {
      providerBaseUrl: 'http://localhost:8080',
      provider: 'PlatformSignupServer',
      providerVersion: '1.0.0',
      pactBrokerUrl: 'http://localhost:9292',
      stateHandlers: {
        'create new product': () => {
          return Promise.resolve([
            {
              accountUuid: 'something',
              realm: 'DIstring',
              userUuid: 'UUID',
            },
          ]);
        },
        'account already exists ': () => {
          // eslint-disable-next-line prefer-promise-reject-errors
          return Promise.reject([
            {
              status: 409,
              error: 'Conflict',
              traceID: '6ca0f6904afa46fb45bdf44f11e0dcf3',
              message: 'Request execution exception, please verify logs',
              timestamp: '2021-11-11T21:21:34.396362421Z',
              errors: [
                {
                  object: 'SignUpRequest',
                  field: 'realm.create',
                  message: 'Realm already exist.',
                },
              ],
            },
          ]);
        },
      },
    };

    if (process.env.CI) {
      Object.assign(opts, {
        publishVerificationResult: true,
      });
    }

    return new Verifier(opts)
      .verifyProvider()
      .then((output) => {
        console.log(output);
      })
      .finally(() => {
        server.close();
      });
  });
});

```
### Relevant log files
json file
```
{
  "consumer": {
    "name": "PlatformSignupClient"
  },
  "provider": {
    "name": "PlatformSignupServer"
  },
  "interactions": [
    {
      "description": "save a new customer",
      "providerState": "user doesnt exist in the database",
      "request": {
        "method": "POST",
        "path": "/api/endpoint",
        "headers": {
          "Content-Type": "application/json",
          "Accept": "application/json"
        },
        "matchingRules": {
          "$.headers.Content-Type": {
            "match": "type"
          },
          "$.headers.Accept": {
            "match": "type"
          }
        }
      },
      "response": {
        "status": 201,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": [
          {
            "accountUuid": "something",
            "realm": "DIstring",
            "userUuid": "UUID"
          }
        ],
        "matchingRules": {
          "$.body": {
            "min": 1
          },
          "$.body[*].*": {
            "match": "type"
          }
        }
      }
    },
    {
      "description": "customer api exception",
      "providerState": "user already exists in the database",
      "request": {
        "method": "POST",
        "path": "/api/endpoint",
        "headers": {
          "Content-Type": "application/json",
          "Accept": "application/json"
        },
        "matchingRules": {
          "$.headers.Content-Type": {
            "match": "type"
          },
          "$.headers.Accept": {
            "match": "type"
          }
        }
      },
      "response": {
        "status": 409,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": [
          {
            "status": 409,
            "error": "Conflict",
            "traceID": "6ca0f6904afa46fb45bdf44f11e0dcf3",
            "message": "Request execution exception, please verify logs",
            "timestamp": "2021-11-11T21:21:34.396362421Z",
            "errors": [
              {
                "object": "SignUpRequest",
                "field": "realm.create",
                "message": "Realm already exist."
              }
            ]
          }
        ],
        "matchingRules": {
          "$.body": {
            "min": 1
          },
          "$.body[*].*": {
            "match": "type"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

**Comment by TimothyJones** [comment] 2021-11-15 21:08
Can you tell us which versions you are using, please? The top of the issue template has the following questions:

* OS: e.g. Mac OSX 10.11.5
* Consumer Pact library: e.g. Pact JS v2.6.0
* Provider Pact library: e.g. pact-jvm-provider-maven_2.11 v 3.3.8

**Comment by TimothyJones** [comment] 2021-11-15 21:15
Also, can you include the full code, please? There isn't enough here to reproduce it, because we don't have several of the files referenced (and as far as I can see, there is nothing like your code in the [pact js workshop](https://github.com/pact-foundation/pact-workshop-js/tree/master/provider)).

Anyway, this is suspicious:

```
router
  .route('/endpoint')
```

Perhaps the error message is correct - should this be `/api/endpoint`?

**Comment by erickbelfy** [comment] 2021-11-15 21:18
I've made a typo, so in the endpoint route it was missing `/api/endpoint`

**Comment by erickbelfy** [comment] 2021-11-15 21:21
So here i gave you the router, the service that calls an external API and the provider that consumes the router, is there anything else I can provide to you in order to test it properly?

**Comment by erickbelfy** [comment] 2021-11-15 21:24
i also updated the version of pact that I'm using, no pact jvm is being used since I'm working with pact-js

**Comment by erickbelfy** [comment] 2021-11-15 21:25
what i'm trying to understand is what exactly I need to pass to the stateHandlers in order to mock the states properly, since I'm calling an external API instead of making a collection of products as the workshop is doing.

**Comment by TimothyJones** [comment] 2021-11-15 21:37
I can't reproduce it if I don't have all the files that are referenced in the code (also, we have a definition for `Signup` but not `SignupAPI` - maybe this is a typo? It may not matter if that's means to be `Signup` because it's a default export). 

>  is there anything else I can provide to you in order to test it properly?

Ideally, with a complex example like this, it's easiest if you can link an example repository that we can run - otherwise we have to guess at what versions of the dependencies you're using, what filenames the files you've included are meant to be, etc - and then we might not be running what you're running. Make it as easy as possible for us to reproduce this.

> what i'm trying to understand is what exactly I need to pass to the stateHandlers in order to mock the states properly, 

It depends on your service code. Returning `Promise.reject()` doesn't look right, though. The state handler is about setting up the state in your application, so it isn't supposed to return a rejected promise unless you failed to set up the state - think of it as a `before` clause in your test. For example, for 'user already exists in the database', you would use the state handler to either set up the database with the user in it database, or you would mock the database layer to return the right user.
 
Also, in your pact file, the states are called `'user already exists in the database'` and `'user doesnt exist in the database'`, but in your test you have `'account already exists '` and `'create new product'`. You aren't setting up any states for the states listed in the pact file (which is probably why it wasn't failing on the rejected promise, because that state handler isn't called).

**Comment by TimothyJones** [comment] 2021-11-15 21:39
> I've made a typo, so in the endpoint route it was missing /api/endpoint

Did this fix the problem?

**Comment by erickbelfy** [comment] 2021-11-15 21:42
> > I've made a typo, so in the endpoint route it was missing /api/endpoint
> 
> Did this fix the problem?

nope it doesn't I just did a typo while providing the example, 

> I can't reproduce it if I don't have all the files that are referenced in the code (also, we have a definition for Signup but not SignupAPI - maybe this is a typo? It may not matter if that's means to be Signup because it's a default export - but I don't know if SignupAPI is meant to be '../../services/signup' or not).

yes, Signup is the file I posted in the example


> Also, in your pact file, the states are called 'user already exists in the database' and 'user doesnt exist in the database', but in your test you have 'account already exists ' and 'create new product'. You aren't setting up any states for the states listed in the pact file (which is probably why it wasn't failing on the rejected promise, because that state handler isn't called).

this means that I need to provide the same state names like I provided in the tests I provided?

**Comment by TimothyJones** [comment] 2021-11-15 21:45
> Let me know if there's anything I can help to improve the understanding of the code 

Please provide a link to a repository that reproduces the problem.

> this means that I need to provide the same state names like I provided in the tests I provided?

Yes, that's right. Pact uses those state strings to set up the preconditions for each test.

**Comment by erickbelfy** [comment] 2021-11-15 21:47
> Please provide a link to a repository that reproduces the problem.

it's a private repo, unfortunately I can't give rights to it, but I try to setup a codesandbox with the example in order to ease up the understanding if it works properly

**Comment by erickbelfy** [comment] 2021-11-15 22:01
https://codesandbox.io/s/hardcore-snyder-lg8qy?file=/src/demo.pact.test.js

here's the codesandbox that includes the code provided in the github description

**Comment by TimothyJones** [comment] 2021-11-15 22:17
I don't see any errors in that sandbox (also, I'm not sure that pact would work in the sandbox, since it needs to fire up it's own server / binaries etc). How are you getting the error?

**Comment by erickbelfy** [comment] 2021-11-15 22:19
this is the error im getting:

```
● Console

    console.log
      /Users/belfoer1/Documents/oss-ui/node_modules/@pact-foundation/pact-node/standalone/darwin-1.88.77/pact/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /Users/belfoer1/Library/Android in PATH, mode 040777

      INFO: Fetching pacts for PlatformSignupServer from http://localhost:9292 with the selection criteria:
      INFO: Reading pact at http://localhost:9292/pacts/provider/PlatformSignupServer/consumer/PlatformSignupClient/pact-version/64c0a1891a3b0b8f328862c3a84782949f8141a6/metadata/c1tdW2xdPXRydWUmc1tdW2N2XT05JnA9dHJ1ZQ

      DEBUG: The pact at http://localhost:9292/pacts/provider/PlatformSignupServer/consumer/PlatformSignupClient/pact-version/64c0a1891a3b0b8f328862c3a84782949f8141a6 is being verified because the pact content belongs to the consumer version matching the following criterion:
          * latest version of PlatformSignupClient that has a pact with PlatformSignupServer (1)
      DEBUG: This pact is in pending state for this version of PlatformSignupServer because a successful verification result for PlatformSignupServer has not yet been published. If this verification fails, it will not cause the overall build to fail. Read more at https://docs.pact.io/go/pending

      Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING]

        Given user doesnt exist in the database
          save a new customer
            with POST /api/endpoint
              returns a response which

                has status code 201 (FAILED - 1)

                has a matching body (FAILED - 2)
                includes headers

                  "Content-Type" which equals "application/json; charset=utf-8" (FAILED - 3)

        Given user already exists in the database

          customer api exception

            with POST /api/endpoint

              returns a response which

                has status code 409 (FAILED - 4)

                has a matching body (FAILED - 5)
                includes headers

                  "Content-Type" which equals "application/json; charset=utf-8" (FAILED - 6)


      Failures:

        1) Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING] Given user doesnt exist in the database save a new customer with POST /api/endpoint returns a response which has status code 201
           Failure/Error: expect(response_status).to eql expected_response_status

             expected: 201
                  got: 500

             (compared using eql?)

        2) Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING] Given user doesnt exist in the database save a new customer with POST /api/endpoint returns a response which has a matching body
           Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example

             Actual: {"message":"No interaction found for POST /api/endpoint","interaction_diffs":[]}

             Diff
             --------------------------------------
             Key: - is expected
                  + is actual
             Matching keys and values are not shown

             -[
             -  {
             -    "accountUuid": "1ee4ba89-06a0-449b-af89-e878e96d8f23",
             -    "realm": "DIstring",
             -    "userUuid": "70bb859c-7de9-430c-b5fb-ffdcc107a0cd"
             -  },
             -]
             +{
             +  "message": "No interaction found for POST /api/endpoint",
             +  "interaction_diffs": [,
             +
             +  ]
             +}


             Description of differences
             --------------------------------------
             * Expected an Array (like [{"accountUuid"=>"1ee4ba89-06a0-449b-af89-e878e96d8f23", "realm"=>"DIstring", "userUuid"=>"70bb859c-7de9-430c-b5fb-ffdcc107a0cd"}]) but got a Hash at $

        3) Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING] Given user doesnt exist in the database save a new customer with POST /api/endpoint returns a response which includes headers "Content-Type" which equals "application/json; charset=utf-8"
           Failure/Error: expect(header_value).to match_header(name, expected_header_value)
             Expected header "Content-Type" to equal "application/json; charset=utf-8", but was "application/json"

        4) Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING] Given user already exists in the database customer api exception with POST /api/endpoint returns a response which has status code 409
           Failure/Error: set_up_provider_states interaction.provider_states, options[:consumer]

           Pact::ProviderVerifier::SetUpProviderStateError:
             Error setting up provider state 'user already exists in the database' for consumer 'PlatformSignupClient' at http://localhost:54778/_pactSetup. response status=500 response body=[{"status":409,"error":"Conflict","traceID":"6ca0f6904afa46fb45bdf44f11e0dcf3","message":"Request execution exception, please verify logs","timestamp":"2021-11-11T21:21:34.396362421Z","errors":[{"object":"SignUpRequest","field":"realm.create","message":"Realm already exist."}]}]

        5) Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING] Given user already exists in the database customer api exception with POST /api/endpoint returns a response which has a matching body
           Failure/Error: set_up_provider_states interaction.provider_states, options[:consumer]

           Pact::ProviderVerifier::SetUpProviderStateError:
             Error setting up provider state 'user already exists in the database' for consumer 'PlatformSignupClient' at http://localhost:54778/_pactSetup. response status=500 response body=[{"status":409,"error":"Conflict","traceID":"6ca0f6904afa46fb45bdf44f11e0dcf3","message":"Request execution exception, please verify logs","timestamp":"2021-11-11T21:21:34.396362421Z","errors":[{"object":"SignUpRequest","field":"realm.create","message":"Realm already exist."}]}]

        6) Verifying a pact between PlatformSignupClient and PlatformSignupServer [PENDING] Given user already exists in the database customer api exception with POST /api/signup returns a response which includes headers "Content-Type" which equals "application/json; charset=utf-8"
           Failure/Error: set_up_provider_states interaction.provider_states, options[:consumer]

           Pact::ProviderVerifier::SetUpProviderStateError:
             Error setting up provider state 'user already exists in the database' for consumer 'PlatformSignupClient' at http://localhost:54778/_pactSetup. response status=500 response body=[{"status":409,"error":"Conflict","traceID":"6ca0f6904afa46fb45bdf44f11e0dcf3","message":"Request execution exception, please verify logs","timestamp":"2021-11-11T21:21:34.396362421Z","errors":[{"object":"SignUpRequest","field":"realm.create","message":"Realm already exist."}]}]


      2 interactions, 0 failures, 2 pending


      Pending interactions: (Failures listed here are expected and do not affect your suite's status)


      * Save a new customer given user doesnt exist in the database (to re-run just this interaction, set environment variable PACT_BROKER_INTERACTION_ID="c090ce86722f69c2bab3e86c5dc39ae7c45a1ca5")
      * Customer api exception given user already exists in the database (to re-run just this interaction, set environment variable PACT_BROKER_INTERACTION_ID="8ac6776c2ced25fa0b7fa3216b97c4b5aa28de7d")

      INFO: Verification results published to http://localhost:9292/pacts/provider/PlatformSignupServer/consumer/PlatformSignupClient/pact-version/64c0a1891a3b0b8f328862c3a84782949f8141a6/verification-results/233
      DEBUG: This pact is still in pending state for PlatformSignupServer as a successful verification result has not yet been published

      at src/demo.pact.test.ts:59:17


Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
```

**Comment by TimothyJones** [comment] 2021-11-15 22:27
Ah! This explains something at least:

```
         +{
             +  "message": "No interaction found for POST /api/endpoint",
             +  "interaction_diffs": [,
             +
             +  ]
             +}        
```             

This diff is telling you what the provider is actually returning during the test, but this message is coming from a Pact consumer test mock(!). So, I suspect there's something misconfigured in the way you're running the test - the provider verification test is supposed to hit your real provider code, not a pact mock. If this is confusing, have a close read of the [provider verification section here](https://docs.pact.io/getting_started/how_pact_works)

I had a look at the sandbox you shared, but it doesn't include the configuration for the test run (or any test runner). 

If this information doesn't help, please share an example repository URL from which I can clone your code and run it to reproduce this problem.

**Comment by erickbelfy** [comment] 2021-11-15 22:35
So there's something i dont understand, the following file copied an inspiration of the workshop example:

```
import { Verifier } from '@pact-foundation/pact';
import express from 'express';
import apiRoutes from './routes';

// Setup provider server to verify
const app = express();
app.use(apiRoutes);

const server = app.listen('8080');

describe('Pact Verification', () => {
  it('validates the expectations of ProductService', () => {
    const opts = {
      providerBaseUrl: 'http://localhost:8080',
      provider: 'PlatformSignupServer',
      providerVersion: '1.0.0',
      pactBrokerUrl: 'http://localhost:9292',
      stateHandlers: {
        'user doesnt exist in the database': () => {
          return Promise.resolve([
            {
              accountUuid: '1ee4ba89-06a0-449b-af89-e878e96d8f23',
              realm: 'DIstring',
              userUuid: '70bb859c-7de9-430c-b5fb-ffdcc107a0cd',
            },
          ]);
        },
        'user already exists in the database': () => {
          // eslint-disable-next-line prefer-promise-reject-errors
          return Promise.reject([
            {
              status: 409,
              error: 'Conflict',
              traceID: '6ca0f6904afa46fb45bdf44f11e0dcf3',
              message: 'Request execution exception, please verify logs',
              timestamp: '2021-11-11T21:21:34.396362421Z',
              errors: [
                {
                  object: 'SignUpRequest',
                  field: 'realm.create',
                  message: 'Realm already exist.',
                },
              ],
            },
          ]);
        },
      },
    };

    if (process.env.CI) {
      Object.assign(opts, {
        publishVerificationResult: true,
      });
    }

    return new Verifier(opts)
      .verifyProvider()
      .then((output) => {
        console.log(output);
      })
      .finally(() => {
        server.close();
      });
  });
});
```
it should spin an express server and it adds the routes into it so when the test passes it destroy the server, why should I have an actual server?

**Comment by TimothyJones** [comment] 2021-11-15 22:42
> it should spin an express server and it adds the routes into it so when the test passes it destroy the server, why should I have an actual server?

Yes, that's right:

```
// Setup provider server to verify
const app = express();
app.use(apiRoutes);

const server = app.listen('8080');
```

^ This part is the bit that starts your actual application (in this example, your application is an express server).

However, there's no error handling in this application startup call, so I suspect what's happening is that you're _also_ running a pact mock server on port 8080, and the `app.listen()` call is silently failing.

**Comment by erickbelfy** [comment] 2021-11-15 22:49
o only have a pact-broker that runs at localhost:9292 how do I know that I'm running a mock server?

**Comment by TimothyJones** [comment] 2021-11-15 22:55
I think you are running a mock server because the provider verification is returning an error that the mock server produces, rather than one that is produced by the code that you've shared.

Perhaps an orphaned one has been left around from a test run that crashed (or was killed) before the clean up ran (`ps aux | grep pact` could tell you if this has happened). Or perhaps your test script starts one up alongside the provider verification. 

It is very hard to tell without sufficient information to reproduce this problem.

**Comment by erickbelfy** [comment] 2021-11-15 23:02
i will try to grind a bit more here, thank you very much, Timothy, for your time spent trying to help me, really good to know that the pact community is very proactive!

**Comment by TimothyJones** [comment] 2021-11-15 23:06
You're welcome. The next place to look (if there are no orphaned mock servers) is the way you're running the tests - I'd expect something simple like `"test": "jest"`, but if there's extra setup that's spawning a mock server then you've got a misconfiguration.

**Comment by erickbelfy** [comment] 2021-11-15 23:07
i will check it out!

**Comment by TimothyJones** [comment] 2021-11-15 23:10
I'll close this for now, since I don't think there's a problem that we can fix in this repository. I've opened an issue on the pact-workshop about clarifying the server setup part of the code - you're right that it is confusing, thanks for letting us know. 

Please feel free to reopen this issue (or file another) if you find anything else that we should fix.

**Closed by TimothyJones** 2021-11-15 23:10 UTC
