### ISSUE TITLE
How to handle password reset contract testing

### ISSUE THREAD

**Issue by skk2142** [pact-foundation/pact-js#417] opened 2020-03-11 10:37 UTC
**This is not a bug**
I'm trying to figure out a way to write a contract test for password reset scenario. Typically, the client sends a token and a new password in the body of the request. To test this, the consumer can send a new password and a random string as a token. However, since the token will be invalid, the provider has to somehow create a new valid token (assuming that it detects that it is a password reset request using stateHandlers). However, I couldn't find a way to modify the body of the incoming request because the body is not exposed in either stateHandlers or requestFilters (or express middleware). 
What's the best way to test this scenario?

**Comment by mefellows** [comment] 2020-03-11 11:00
Are you sure that you can't modify the body in a [`requestFilter`](https://github.com/pact-foundation/pact-js#modify-requests-prior-to-verification-request-filters)? It should be an express compatible middleware. 

I also assume you've read https://docs.pact.io/provider/handling_auth ?

**Comment by TimothyJones** [comment] 2020-03-11 14:56
For this kind of situation, I use a provider state like `token SOME_TOKEN_VALUE is a valid password reset token`. then I send `SOME_TOKEN_VALUE` explicitly in the client test.

Depending on your provider design, you could either create the token, or stub the token repository in the state handler.

**Comment by mefellows** [comment] 2020-03-11 19:50
That's a good point Tim. I got stuck on the bug description but that's
worth noting. The docs discuss the tradeoffs of the various approaches

**Comment by skk2142** [comment] 2020-03-20 08:22
Sorry for a late response @mefellows. I have tried request filter but the request body looks like this:
```javascript
{
      consumer: 'EmailService',
      state: 'user with id awkuhcfa87w4r exists',
      states: [ 'user with id awkuhcfa87w4r exists' ],
      params: {}
 }
```
It does not have the actually body of the post request.
@TimothyJones I'll think more about that approach.

**Comment by mefellows** [comment] 2020-03-20 10:11
That is the body of a state handler (not a request filter) @skk2142, I'm guessing you've perhaps wired something up wrong? Could you please provide the code that is giving you that?

**Comment by skk2142** [comment] 2020-03-20 10:23
The gave you the `console.log(req.body);` from requestFilter option
```javascript
const stateHandlers: VerifierOptions['stateHandlers'] = {
  'default state': async () => {
    await resetDb();
    await seedDb();
  },
  'no state': async () => {
    await resetDb();
    await seedDb();
  },
  'user does not exist': async () => {
    await resetDb();
    await seedDb();
  },
  'public group with invitation id 2291a958-108e-478c-b74f-f8ea663b51d6 and userId 1234123': async () => {
    await resetDb();
    await seedDb();
    await createUser({ id: '1234123' });
    await createEmailInvitation({
      groupId: groups.PUBLIC_GROUP_ID,
      invitedByUserId: users.PUBLIC_GROUP_OWNER_ID,
      id: '2291a958-108e-478c-b74f-f8ea663b51d6',
    });
  },
  'user with id awkuhcfa87w4r exists': async () => {
    await resetDb();
    await seedDb();
    await createUser({ id: 'awkuhcfa87w4r' });
  },
};

const gitHash =
  process.env.GIT_COMMIT ||
  require('child_process')
    .execSync('git rev-parse --short HEAD')
    .toString()
    .trim();

const tags: string[] = [];
if (process.env.CI && process.env.BRANCH_NAME) {
  tags.push(process.env.BRANCH_NAME);
}

if (!process.env.CI) {
  tags.push('dev');
}
describe('Pact verification', () => {
  test('validates the expectations of GroupService', async () => {
    jest.setTimeout(30000);
    const logLevel: VerifierOptions['logLevel'] = 'info';
    const opts: VerifierOptions = {
      logLevel,
      providerBaseUrl: `http://localhost:${PORT}`,
      provider: 'GroupService',
      providerVersion: gitHash,
      // tags,
      consumerVersionTag: tags,
      providerVersionTag: tags,
      // pactUrls: [path.resolve(__dirname, "gateway-authservice.json")]
      stateHandlers,
      requestFilter: (
        req: express.Request,
        res: express.Response,
        next: express.NextFunction,
      ) => {
        console.log(req.body);
        next();
      },
      pactBrokerUrl: config.PACT_BROKER_URL,
      pactBrokerToken: config.PACT_BROKER_TOKEN,
      // pactBrokerUsername: config.PACT_BROKER_USERNAME,
      // pactBrokerPassword: config.PACT_BROKER_PASSWORD
    };
    // add
    if (process.env.CI || process.env.PACT_PUBLISH_RESULTS) {
      Object.assign(opts, {
        publishVerificationResult: true,
      });
    }

    return new Verifier(opts).verifyProvider().finally(() => {
      app.stop();
    });
  });
});
```

**Comment by mefellows** [comment] 2020-03-20 10:38
Ha! OK, so the state handler - funnily enough - also passes through this filter. So what you're seeing is the _state setup_ coming in to the system. You'll probably want to ignore that payload, because just after you should get the _real_ incoming payload.

This is probably not ideal behaviour, and is certainly not documented, but it currently is the case. I'm wondering if that is worth excluding from the middleware as it stands today (for v3 implementation, this definitely won't be the case - and I do explictly ignore it in Pact Go also).

**Comment by skk2142** [comment] 2020-03-20 11:45
oh I see. That's indeed the case for the state handler payload. However, the payload that comes with the real request has the body `undefined`. 
First I get the log for the state, then the seed logs (which is from the state handler), and then `undefined`. Any idea why?
```
console.log src/provider.pact.test.ts:91
    {
      consumer: 'Frontend',
      state: 'public group with invitation id 2291a958-108e-478c-b74f-f8ea663b51d6 and userId 1234123',
      states: [
        'public group with invitation id 2291a958-108e-478c-b74f-f8ea663b51d6 and userId 1234123'
      ],
      params: {}
    }

  console.log src/db/seeds/index.ts:1002
    👏 seeding done

  console.log src/provider.pact.test.ts:91
    undefined

```

**Comment by mefellows** [comment] 2020-03-21 08:18
Hmm strange.

Any chance you could try to demonstrate your issue with the e2e test in the repo? That will help us narrow it down quickly. 

Is it possible there _is_ no request body for that request? Is the request of `req` present and just the body is undefined?

**Comment by skk2142** [comment] 2020-03-21 20:30
Okay, I'll create a repo soon. I get this error for all post requests with body.

**Comment by c-magri** [comment] 2020-08-10 08:40
i have the same issue, req.body is undefined

**Comment by mefellows** [comment] 2020-08-10 09:20
Can you please provide a reproducible example? Use the e2e test in this repository to demonstrate your problem.

**Comment by c-magri** [comment] 2020-08-10 09:37
I will try to provide an example, but there is an example in here too https://github.com/pact-foundation/pact-js/issues/304#issuecomment-501478306

**Comment by c-magri** [comment] 2020-08-10 13:08
@mefellows i created an example https://github.com/c-magri/pact-js/blob/master/examples/e2e/test/provider.spec.js#L28-L32 as seen in these lines `req.body` is undefined and there is no way to set it up.

**Comment by mefellows** [comment] 2020-08-10 13:17
Thanks. As discussed before (in the other thread), `req.body` isn't automatically parsed. I think at the least, we should parse the body. Looking at the problem before, it may be an issue with the way the http proxy wires in to the process - right now, changing the body makes it hang. I suspect this is due to an event not being fired/closed on the event loop.

Definitely a bugy.

**Comment by mefellows** [comment] 2020-08-10 13:19
Going to close this in favour of #304.

**Closed by mefellows** 2020-08-10 13:19 UTC
Labels: Awaiting feedback, Triage
